export const nnsdaoKeys = {
  all: [{ module: 'nnsdao' }] as const,
  userInfo: () => [{ ...nnsdaoKeys.all[0], scope: 'userInfo' }] as const,
  userInfos: () => [{ ...nnsdaoKeys.userInfos()[0] }] as const,
  vote: () => [{ ...nnsdaoKeys.all[0], scope: 'vote' }] as const,
  votes: () => [{ ...nnsdaoKeys.votes()[0] }] as const,
  quit: () => [{ ...nnsdaoKeys.all[0], scope: 'quit' }] as const,
  quits: () => [{ ...nnsdaoKeys.quits()[0] }] as const,
  propose: () => [{ ...nnsdaoKeys.all[0], scope: 'propose' }] as const,
  proposes: () => [{ ...nnsdaoKeys.proposes()[0] }] as const,
  member_list: () => [{ ...nnsdaoKeys.all[0], scope: 'member_list' }] as const,
  member_lists: () => [{ ...nnsdaoKeys.member_lists()[0] }] as const,
  join: () => [{ ...nnsdaoKeys.all[0], scope: 'join' }] as const,
  joins: () => [{ ...nnsdaoKeys.joins()[0] }] as const,
  get_proposal: () => [{ ...nnsdaoKeys.all[0], scope: 'get_proposal' }] as const,
  get_proposals: () => [{ ...nnsdaoKeys.get_proposals()[0] }] as const,
  get_handled_proposal: () => [{ ...nnsdaoKeys.all[0], scope: 'get_handled_proposal' }] as const,
  get_handled_proposals: () => [{ ...nnsdaoKeys.get_handled_proposals()[0] }] as const,
};
