export const nnsdaoKeys = {
  all: [{ module: 'nnsdao' }] as const,
  userInfo: () => [{ ...nnsdaoKeys.all, scope: 'userInfo' }] as const,
  userInfos: () => [{ ...nnsdaoKeys.userInfos() }] as const,
  vote: () => [{ ...nnsdaoKeys.all, scope: 'vote' }] as const,
  votes: () => [{ ...nnsdaoKeys.votes() }] as const,
  quit: () => [{ ...nnsdaoKeys.all, scope: 'quit' }] as const,
  quits: () => [{ ...nnsdaoKeys.quits() }] as const,
  propose: () => [{ ...nnsdaoKeys.all, scope: 'propose' }] as const,
  proposes: () => [{ ...nnsdaoKeys.proposes() }] as const,
  member_list: () => [{ ...nnsdaoKeys.all, scope: 'member_list' }] as const,
  member_lists: () => [{ ...nnsdaoKeys.member_lists() }] as const,
  join: () => [{ ...nnsdaoKeys.all, scope: 'join' }] as const,
  joins: () => [{ ...nnsdaoKeys.joins() }] as const,
  get_proposal: () => [{ ...nnsdaoKeys.all, scope: 'get_proposal' }] as const,
  get_proposals: () => [{ ...nnsdaoKeys.get_proposals() }] as const,
  get_handled_proposal: () => [{ ...nnsdaoKeys.all, scope: 'get_handled_proposal' }] as const,
  get_handled_proposals: () => [{ ...nnsdaoKeys.get_handled_proposals() }] as const,

  getProposalList: () => [{ ...nnsdaoKeys.all, scope: 'get_proposal_list' }] as const,
  getProposalLists: () => [{ ...nnsdaoKeys.getProposalLists() }] as const,
};
